# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = [
  "github.com/ernestio/ernestprovider/.",
  "github.com/ernestio/ernestprovider/event",
  "github.com/ernestio/ernestprovider/providers/azure/availabilityset",
  "github.com/ernestio/ernestprovider/providers/azure/lb",
  "github.com/ernestio/ernestprovider/providers/azure/lbbackendaddresspool",
  "github.com/ernestio/ernestprovider/providers/azure/lbprobe",
  "github.com/ernestio/ernestprovider/providers/azure/lbrule",
  "github.com/ernestio/ernestprovider/providers/azure/localnetworkgateway",
  "github.com/ernestio/ernestprovider/providers/azure/manageddisk",
  "github.com/ernestio/ernestprovider/providers/azure/networkinterface",
  "github.com/ernestio/ernestprovider/providers/azure/publicip",
  "github.com/ernestio/ernestprovider/providers/azure/resourcegroup",
  "github.com/ernestio/ernestprovider/providers/azure/securitygroup",
  "github.com/ernestio/ernestprovider/providers/azure/sqldatabase",
  "github.com/ernestio/ernestprovider/providers/azure/sqlfirewallrule",
  "github.com/ernestio/ernestprovider/providers/azure/sqlserver",
  "github.com/ernestio/ernestprovider/providers/azure/storageaccount",
  "github.com/ernestio/ernestprovider/providers/azure/storagecontainer",
  "github.com/ernestio/ernestprovider/providers/azure/subnet",
  "github.com/ernestio/ernestprovider/providers/azure/virtualmachine",
  "github.com/ernestio/ernestprovider/providers/azure/virtualnetwork",
]

[[constraint]]
  branch = "master"
  name = "github.com/ernestio/ernest-config-client"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/nats-io/nats"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/r3labs/akira"

[[constraint]]
  name = "github.com/r3labs/binary-prefix"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/r3labs/diff"

[[constraint]]
  branch = "master"
  name = "github.com/r3labs/graph"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "isolate_entities"
  name = "github.com/ernestio/ernestprovider"
